---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cockroachdb
  namespace: argocd
spec:
  generators:
  # Generator for both clusters
  - list:
      elements:
      - cluster: k3d-dc-us
        url: https://kubernetes.default.svc
        region: us-east-1
        locality: "region=us-east-1"
      - cluster: k3d-dc-eu
        url: https://kubernetes.default.svc
        region: eu-central-1
        locality: "region=eu-central-1"
  
  template:
    metadata:
      name: '{{cluster}}-cockroachdb'
      labels:
        app: cockroachdb
        region: '{{region}}'
    spec:
      project: default
      source:
        repoURL: file:///gitops
        targetRevision: HEAD
        path: charts/cockroachdb
        helm:
          valueFiles:
            - values.yaml
          values: |
            region:
              name: {{region}}
              locality: {{locality}}
            storage:
              persistentVolume:
                size: 10Gi
            resources:
              requests:
                cpu: "500m"
                memory: "512Mi"
              limits:
                cpu: "2000m"
                memory: "1Gi"
      destination:
        server: '{{url}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true

